stages:
  - build
  - deploy

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
    - docker build -t huanligong/qa-api:latest .
    - docker push huanligong/qa-api:latest
  only:
    - main

deploy:
  stage: deploy
  image: google/cloud-sdk:latest
  script:
    - echo $GKE_SERVICE_KEY > gcloud-service-key.json
    - gcloud auth activate-service-account --key-file gcloud-service-key.json
    - gcloud container clusters get-credentials test-cluster --zone  us-central1-a --project ghl000125
    - kubectl apply -f kubernetes.yaml
    - kubectl get deployments
    - kubectl get pods -l app=qa-api
    - kubectl get svc
  only:
    - main

